# coding: utf-8

"""
    Main - Floriday Suppliers API

    ﻿Every endpoint requires at least the `role:app` scope and the header `X-Api-Key` populated with your given API-key. Most endpoints also require an additional scope which is listed in their descriptions.  - 🗝 [Authorization server (staging)](https://idm.staging.floriday.io/oauth2/ausmw6b47z1BnlHkw0h7/.well-known/oauth-authorization-server) - 🗝 [Authorization server (live)](https://idm.floriday.io/oauth2/aus3testdcf2vyfs70i7/.well-known/oauth-authorization-server) - 📚 [Documentation](https://developer.floriday.io/docs/welcome) - ▶ [Coding screencast: getting started (NL)](https://www.youtube.com/watch?v=fdqzP7_Y_s8)  ---  _The current state of this version 2024v1 is **Main**._ * This version will be deprecated after October 2024. * This version will be removed after April 2025.  ---  🔗 2023v2: [Customers API](https://api.staging.floriday.io/customers-api-2023v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2023v2/swagger/index.html) 🔗 2024v1: [Customers API](https://api.staging.floriday.io/customers-api-2024v1/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v1/swagger/index.html) 🔗 2024v2: [Customers API](https://api.staging.floriday.io/customers-api-2024v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v2/swagger/index.html)   # noqa: E501

    OpenAPI spec version: 2024v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddOrEditBundledOfferLine(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bundled_offer_line_id': 'str',
        'trade_item_id': 'str',
        'price': 'Price',
        'number_of_pieces_per_bundle': 'int',
        'packing_configuration': 'PackingConfiguration'
    }

    attribute_map = {
        'bundled_offer_line_id': 'bundledOfferLineId',
        'trade_item_id': 'tradeItemId',
        'price': 'price',
        'number_of_pieces_per_bundle': 'numberOfPiecesPerBundle',
        'packing_configuration': 'packingConfiguration'
    }

    def __init__(self, bundled_offer_line_id=None, trade_item_id=None, price=None, number_of_pieces_per_bundle=None, packing_configuration=None):  # noqa: E501
        """AddOrEditBundledOfferLine - a model defined in Swagger"""  # noqa: E501
        self._bundled_offer_line_id = None
        self._trade_item_id = None
        self._price = None
        self._number_of_pieces_per_bundle = None
        self._packing_configuration = None
        self.discriminator = None
        self.bundled_offer_line_id = bundled_offer_line_id
        self.trade_item_id = trade_item_id
        self.price = price
        self.number_of_pieces_per_bundle = number_of_pieces_per_bundle
        self.packing_configuration = packing_configuration

    @property
    def bundled_offer_line_id(self):
        """Gets the bundled_offer_line_id of this AddOrEditBundledOfferLine.  # noqa: E501


        :return: The bundled_offer_line_id of this AddOrEditBundledOfferLine.  # noqa: E501
        :rtype: str
        """
        return self._bundled_offer_line_id

    @bundled_offer_line_id.setter
    def bundled_offer_line_id(self, bundled_offer_line_id):
        """Sets the bundled_offer_line_id of this AddOrEditBundledOfferLine.


        :param bundled_offer_line_id: The bundled_offer_line_id of this AddOrEditBundledOfferLine.  # noqa: E501
        :type: str
        """
        if bundled_offer_line_id is None:
            raise ValueError("Invalid value for `bundled_offer_line_id`, must not be `None`")  # noqa: E501

        self._bundled_offer_line_id = bundled_offer_line_id

    @property
    def trade_item_id(self):
        """Gets the trade_item_id of this AddOrEditBundledOfferLine.  # noqa: E501


        :return: The trade_item_id of this AddOrEditBundledOfferLine.  # noqa: E501
        :rtype: str
        """
        return self._trade_item_id

    @trade_item_id.setter
    def trade_item_id(self, trade_item_id):
        """Sets the trade_item_id of this AddOrEditBundledOfferLine.


        :param trade_item_id: The trade_item_id of this AddOrEditBundledOfferLine.  # noqa: E501
        :type: str
        """
        if trade_item_id is None:
            raise ValueError("Invalid value for `trade_item_id`, must not be `None`")  # noqa: E501

        self._trade_item_id = trade_item_id

    @property
    def price(self):
        """Gets the price of this AddOrEditBundledOfferLine.  # noqa: E501


        :return: The price of this AddOrEditBundledOfferLine.  # noqa: E501
        :rtype: Price
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this AddOrEditBundledOfferLine.


        :param price: The price of this AddOrEditBundledOfferLine.  # noqa: E501
        :type: Price
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def number_of_pieces_per_bundle(self):
        """Gets the number_of_pieces_per_bundle of this AddOrEditBundledOfferLine.  # noqa: E501


        :return: The number_of_pieces_per_bundle of this AddOrEditBundledOfferLine.  # noqa: E501
        :rtype: int
        """
        return self._number_of_pieces_per_bundle

    @number_of_pieces_per_bundle.setter
    def number_of_pieces_per_bundle(self, number_of_pieces_per_bundle):
        """Sets the number_of_pieces_per_bundle of this AddOrEditBundledOfferLine.


        :param number_of_pieces_per_bundle: The number_of_pieces_per_bundle of this AddOrEditBundledOfferLine.  # noqa: E501
        :type: int
        """
        if number_of_pieces_per_bundle is None:
            raise ValueError("Invalid value for `number_of_pieces_per_bundle`, must not be `None`")  # noqa: E501

        self._number_of_pieces_per_bundle = number_of_pieces_per_bundle

    @property
    def packing_configuration(self):
        """Gets the packing_configuration of this AddOrEditBundledOfferLine.  # noqa: E501


        :return: The packing_configuration of this AddOrEditBundledOfferLine.  # noqa: E501
        :rtype: PackingConfiguration
        """
        return self._packing_configuration

    @packing_configuration.setter
    def packing_configuration(self, packing_configuration):
        """Sets the packing_configuration of this AddOrEditBundledOfferLine.


        :param packing_configuration: The packing_configuration of this AddOrEditBundledOfferLine.  # noqa: E501
        :type: PackingConfiguration
        """
        if packing_configuration is None:
            raise ValueError("Invalid value for `packing_configuration`, must not be `None`")  # noqa: E501

        self._packing_configuration = packing_configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddOrEditBundledOfferLine, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddOrEditBundledOfferLine):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
