# coding: utf-8

"""
    Main - Floriday Suppliers API

    ﻿Every endpoint requires at least the `role:app` scope and the header `X-Api-Key` populated with your given API-key. Most endpoints also require an additional scope which is listed in their descriptions.  - 🗝 [Authorization server (staging)](https://idm.staging.floriday.io/oauth2/ausmw6b47z1BnlHkw0h7/.well-known/oauth-authorization-server) - 🗝 [Authorization server (live)](https://idm.floriday.io/oauth2/aus3testdcf2vyfs70i7/.well-known/oauth-authorization-server) - 📚 [Documentation](https://developer.floriday.io/docs/welcome) - ▶ [Coding screencast: getting started (NL)](https://www.youtube.com/watch?v=fdqzP7_Y_s8)  ---  _The current state of this version 2024v1 is **Main**._ * This version will be deprecated after October 2024. * This version will be removed after April 2025.  ---  🔗 2023v2: [Customers API](https://api.staging.floriday.io/customers-api-2023v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2023v2/swagger/index.html) 🔗 2024v1: [Customers API](https://api.staging.floriday.io/customers-api-2024v1/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v1/swagger/index.html) 🔗 2024v2: [Customers API](https://api.staging.floriday.io/customers-api-2024v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v2/swagger/index.html)   # noqa: E501

    OpenAPI spec version: 2024v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryOrderGoodsMovement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fulfillment_requests': 'list[FulfillmentRequestCreate]',
        'delivery_date_time': 'datetime',
        'destination_warehouse_id': 'str',
        'despatch_warehouse_id': 'str'
    }

    attribute_map = {
        'fulfillment_requests': 'fulfillmentRequests',
        'delivery_date_time': 'deliveryDateTime',
        'destination_warehouse_id': 'destinationWarehouseId',
        'despatch_warehouse_id': 'despatchWarehouseId'
    }

    def __init__(self, fulfillment_requests=None, delivery_date_time=None, destination_warehouse_id=None, despatch_warehouse_id=None):  # noqa: E501
        """DeliveryOrderGoodsMovement - a model defined in Swagger"""  # noqa: E501
        self._fulfillment_requests = None
        self._delivery_date_time = None
        self._destination_warehouse_id = None
        self._despatch_warehouse_id = None
        self.discriminator = None
        self.fulfillment_requests = fulfillment_requests
        self.delivery_date_time = delivery_date_time
        self.destination_warehouse_id = destination_warehouse_id
        self.despatch_warehouse_id = despatch_warehouse_id

    @property
    def fulfillment_requests(self):
        """Gets the fulfillment_requests of this DeliveryOrderGoodsMovement.  # noqa: E501


        :return: The fulfillment_requests of this DeliveryOrderGoodsMovement.  # noqa: E501
        :rtype: list[FulfillmentRequestCreate]
        """
        return self._fulfillment_requests

    @fulfillment_requests.setter
    def fulfillment_requests(self, fulfillment_requests):
        """Sets the fulfillment_requests of this DeliveryOrderGoodsMovement.


        :param fulfillment_requests: The fulfillment_requests of this DeliveryOrderGoodsMovement.  # noqa: E501
        :type: list[FulfillmentRequestCreate]
        """
        if fulfillment_requests is None:
            raise ValueError("Invalid value for `fulfillment_requests`, must not be `None`")  # noqa: E501

        self._fulfillment_requests = fulfillment_requests

    @property
    def delivery_date_time(self):
        """Gets the delivery_date_time of this DeliveryOrderGoodsMovement.  # noqa: E501


        :return: The delivery_date_time of this DeliveryOrderGoodsMovement.  # noqa: E501
        :rtype: datetime
        """
        return self._delivery_date_time

    @delivery_date_time.setter
    def delivery_date_time(self, delivery_date_time):
        """Sets the delivery_date_time of this DeliveryOrderGoodsMovement.


        :param delivery_date_time: The delivery_date_time of this DeliveryOrderGoodsMovement.  # noqa: E501
        :type: datetime
        """
        if delivery_date_time is None:
            raise ValueError("Invalid value for `delivery_date_time`, must not be `None`")  # noqa: E501

        self._delivery_date_time = delivery_date_time

    @property
    def destination_warehouse_id(self):
        """Gets the destination_warehouse_id of this DeliveryOrderGoodsMovement.  # noqa: E501


        :return: The destination_warehouse_id of this DeliveryOrderGoodsMovement.  # noqa: E501
        :rtype: str
        """
        return self._destination_warehouse_id

    @destination_warehouse_id.setter
    def destination_warehouse_id(self, destination_warehouse_id):
        """Sets the destination_warehouse_id of this DeliveryOrderGoodsMovement.


        :param destination_warehouse_id: The destination_warehouse_id of this DeliveryOrderGoodsMovement.  # noqa: E501
        :type: str
        """
        if destination_warehouse_id is None:
            raise ValueError("Invalid value for `destination_warehouse_id`, must not be `None`")  # noqa: E501

        self._destination_warehouse_id = destination_warehouse_id

    @property
    def despatch_warehouse_id(self):
        """Gets the despatch_warehouse_id of this DeliveryOrderGoodsMovement.  # noqa: E501


        :return: The despatch_warehouse_id of this DeliveryOrderGoodsMovement.  # noqa: E501
        :rtype: str
        """
        return self._despatch_warehouse_id

    @despatch_warehouse_id.setter
    def despatch_warehouse_id(self, despatch_warehouse_id):
        """Sets the despatch_warehouse_id of this DeliveryOrderGoodsMovement.


        :param despatch_warehouse_id: The despatch_warehouse_id of this DeliveryOrderGoodsMovement.  # noqa: E501
        :type: str
        """
        if despatch_warehouse_id is None:
            raise ValueError("Invalid value for `despatch_warehouse_id`, must not be `None`")  # noqa: E501

        self._despatch_warehouse_id = despatch_warehouse_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryOrderGoodsMovement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryOrderGoodsMovement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
