# coding: utf-8

"""
    Main - Floriday Suppliers API

    ﻿Every endpoint requires at least the `role:app` scope and the header `X-Api-Key` populated with your given API-key. Most endpoints also require an additional scope which is listed in their descriptions.  - 🗝 [Authorization server (staging)](https://idm.staging.floriday.io/oauth2/ausmw6b47z1BnlHkw0h7/.well-known/oauth-authorization-server) - 🗝 [Authorization server (live)](https://idm.floriday.io/oauth2/aus3testdcf2vyfs70i7/.well-known/oauth-authorization-server) - 📚 [Documentation](https://developer.floriday.io/docs/welcome) - ▶ [Coding screencast: getting started (NL)](https://www.youtube.com/watch?v=fdqzP7_Y_s8)  ---  _The current state of this version 2025v1 is **Main**._ * This version will be main after April 2025. * This version will be deprecated after October 2025. * This version will be removed after April 2026.  ---  🔗 2024v2: [Customers API](https://api.staging.floriday.io/customers-api-2024v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v2/swagger/index.html) 🔗 2025v1: [Customers API](https://api.staging.floriday.io/customers-api-2025v1/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2025v1/swagger/index.html) 🔗 2025v2: [Customers API](https://api.staging.floriday.io/customers-api-2025v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2025v2/swagger/index.html)   # noqa: E501

    OpenAPI spec version: 2025v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddBatchFromTradeItemProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'batch_id': 'str',
        'batch_date': 'datetime',
        'number_of_pieces': 'int',
        'batch_reference': 'str',
        'custom_reference': 'str',
        'warehouse_id': 'str',
        'image_url': 'str',
        'vbn_product_code': 'int',
        'characteristics': 'list[Characteristic]',
        'packing_configuration': 'AddBatchPackingConfiguration'
    }

    attribute_map = {
        'batch_id': 'batchId',
        'batch_date': 'batchDate',
        'number_of_pieces': 'numberOfPieces',
        'batch_reference': 'batchReference',
        'custom_reference': 'customReference',
        'warehouse_id': 'warehouseId',
        'image_url': 'imageUrl',
        'vbn_product_code': 'vbnProductCode',
        'characteristics': 'characteristics',
        'packing_configuration': 'packingConfiguration'
    }

    def __init__(self, batch_id=None, batch_date=None, number_of_pieces=None, batch_reference=None, custom_reference=None, warehouse_id=None, image_url=None, vbn_product_code=None, characteristics=None, packing_configuration=None):  # noqa: E501
        """AddBatchFromTradeItemProperties - a model defined in Swagger"""  # noqa: E501
        self._batch_id = None
        self._batch_date = None
        self._number_of_pieces = None
        self._batch_reference = None
        self._custom_reference = None
        self._warehouse_id = None
        self._image_url = None
        self._vbn_product_code = None
        self._characteristics = None
        self._packing_configuration = None
        self.discriminator = None
        self.batch_id = batch_id
        self.batch_date = batch_date
        self.number_of_pieces = number_of_pieces
        if batch_reference is not None:
            self.batch_reference = batch_reference
        if custom_reference is not None:
            self.custom_reference = custom_reference
        self.warehouse_id = warehouse_id
        if image_url is not None:
            self.image_url = image_url
        self.vbn_product_code = vbn_product_code
        self.characteristics = characteristics
        self.packing_configuration = packing_configuration

    @property
    def batch_id(self):
        """Gets the batch_id of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The batch_id of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: str
        """
        return self._batch_id

    @batch_id.setter
    def batch_id(self, batch_id):
        """Sets the batch_id of this AddBatchFromTradeItemProperties.


        :param batch_id: The batch_id of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: str
        """
        if batch_id is None:
            raise ValueError("Invalid value for `batch_id`, must not be `None`")  # noqa: E501

        self._batch_id = batch_id

    @property
    def batch_date(self):
        """Gets the batch_date of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The batch_date of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: datetime
        """
        return self._batch_date

    @batch_date.setter
    def batch_date(self, batch_date):
        """Sets the batch_date of this AddBatchFromTradeItemProperties.


        :param batch_date: The batch_date of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: datetime
        """
        if batch_date is None:
            raise ValueError("Invalid value for `batch_date`, must not be `None`")  # noqa: E501

        self._batch_date = batch_date

    @property
    def number_of_pieces(self):
        """Gets the number_of_pieces of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The number_of_pieces of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: int
        """
        return self._number_of_pieces

    @number_of_pieces.setter
    def number_of_pieces(self, number_of_pieces):
        """Sets the number_of_pieces of this AddBatchFromTradeItemProperties.


        :param number_of_pieces: The number_of_pieces of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: int
        """
        if number_of_pieces is None:
            raise ValueError("Invalid value for `number_of_pieces`, must not be `None`")  # noqa: E501

        self._number_of_pieces = number_of_pieces

    @property
    def batch_reference(self):
        """Gets the batch_reference of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The batch_reference of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: str
        """
        return self._batch_reference

    @batch_reference.setter
    def batch_reference(self, batch_reference):
        """Sets the batch_reference of this AddBatchFromTradeItemProperties.


        :param batch_reference: The batch_reference of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: str
        """

        self._batch_reference = batch_reference

    @property
    def custom_reference(self):
        """Gets the custom_reference of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The custom_reference of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: str
        """
        return self._custom_reference

    @custom_reference.setter
    def custom_reference(self, custom_reference):
        """Sets the custom_reference of this AddBatchFromTradeItemProperties.


        :param custom_reference: The custom_reference of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: str
        """

        self._custom_reference = custom_reference

    @property
    def warehouse_id(self):
        """Gets the warehouse_id of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The warehouse_id of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: str
        """
        return self._warehouse_id

    @warehouse_id.setter
    def warehouse_id(self, warehouse_id):
        """Sets the warehouse_id of this AddBatchFromTradeItemProperties.


        :param warehouse_id: The warehouse_id of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: str
        """
        if warehouse_id is None:
            raise ValueError("Invalid value for `warehouse_id`, must not be `None`")  # noqa: E501

        self._warehouse_id = warehouse_id

    @property
    def image_url(self):
        """Gets the image_url of this AddBatchFromTradeItemProperties.  # noqa: E501

        Image URLs posted as Floriday media must conform with the following format https://image.floriday.io/.  # noqa: E501

        :return: The image_url of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this AddBatchFromTradeItemProperties.

        Image URLs posted as Floriday media must conform with the following format https://image.floriday.io/.  # noqa: E501

        :param image_url: The image_url of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    @property
    def vbn_product_code(self):
        """Gets the vbn_product_code of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The vbn_product_code of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: int
        """
        return self._vbn_product_code

    @vbn_product_code.setter
    def vbn_product_code(self, vbn_product_code):
        """Sets the vbn_product_code of this AddBatchFromTradeItemProperties.


        :param vbn_product_code: The vbn_product_code of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: int
        """
        if vbn_product_code is None:
            raise ValueError("Invalid value for `vbn_product_code`, must not be `None`")  # noqa: E501

        self._vbn_product_code = vbn_product_code

    @property
    def characteristics(self):
        """Gets the characteristics of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The characteristics of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: list[Characteristic]
        """
        return self._characteristics

    @characteristics.setter
    def characteristics(self, characteristics):
        """Sets the characteristics of this AddBatchFromTradeItemProperties.


        :param characteristics: The characteristics of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: list[Characteristic]
        """
        if characteristics is None:
            raise ValueError("Invalid value for `characteristics`, must not be `None`")  # noqa: E501

        self._characteristics = characteristics

    @property
    def packing_configuration(self):
        """Gets the packing_configuration of this AddBatchFromTradeItemProperties.  # noqa: E501


        :return: The packing_configuration of this AddBatchFromTradeItemProperties.  # noqa: E501
        :rtype: AddBatchPackingConfiguration
        """
        return self._packing_configuration

    @packing_configuration.setter
    def packing_configuration(self, packing_configuration):
        """Sets the packing_configuration of this AddBatchFromTradeItemProperties.


        :param packing_configuration: The packing_configuration of this AddBatchFromTradeItemProperties.  # noqa: E501
        :type: AddBatchPackingConfiguration
        """
        if packing_configuration is None:
            raise ValueError("Invalid value for `packing_configuration`, must not be `None`")  # noqa: E501

        self._packing_configuration = packing_configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddBatchFromTradeItemProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddBatchFromTradeItemProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
