# coding: utf-8

"""
    Main - Floriday Suppliers API

    ﻿Every endpoint requires at least the `role:app` scope and the header `X-Api-Key` populated with your given API-key. Most endpoints also require an additional scope which is listed in their descriptions.  - 🗝 [Authorization server (staging)](https://idm.staging.floriday.io/oauth2/ausmw6b47z1BnlHkw0h7/.well-known/oauth-authorization-server) - 🗝 [Authorization server (live)](https://idm.floriday.io/oauth2/aus3testdcf2vyfs70i7/.well-known/oauth-authorization-server) - 📚 [Documentation](https://developer.floriday.io/docs/welcome) - ▶ [Coding screencast: getting started (NL)](https://www.youtube.com/watch?v=fdqzP7_Y_s8)  ---  _The current state of this version 2024v2 is **Main**._ * This version will be deprecated after April 2025. * This version will be removed after October 2025.  ---  🔗 2024v1: [Customers API](https://api.staging.floriday.io/customers-api-2024v1/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v1/swagger/index.html) 🔗 2024v2: [Customers API](https://api.staging.floriday.io/customers-api-2024v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v2/swagger/index.html)   # noqa: E501

    OpenAPI spec version: 2024v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BatchBaseSupplyPriceGroupPrice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'supply_line_id': 'str',
        'price_group_id': 'str',
        'price_per_piece': 'Price',
        'price_group_type': 'PriceGroupType',
        'price_per_piece_last_modified': 'datetime'
    }

    attribute_map = {
        'supply_line_id': 'supplyLineId',
        'price_group_id': 'priceGroupId',
        'price_per_piece': 'pricePerPiece',
        'price_group_type': 'priceGroupType',
        'price_per_piece_last_modified': 'pricePerPieceLastModified'
    }

    def __init__(self, supply_line_id=None, price_group_id=None, price_per_piece=None, price_group_type=None, price_per_piece_last_modified=None):  # noqa: E501
        """BatchBaseSupplyPriceGroupPrice - a model defined in Swagger"""  # noqa: E501
        self._supply_line_id = None
        self._price_group_id = None
        self._price_per_piece = None
        self._price_group_type = None
        self._price_per_piece_last_modified = None
        self.discriminator = None
        self.supply_line_id = supply_line_id
        self.price_group_id = price_group_id
        self.price_per_piece = price_per_piece
        self.price_group_type = price_group_type
        self.price_per_piece_last_modified = price_per_piece_last_modified

    @property
    def supply_line_id(self):
        """Gets the supply_line_id of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501


        :return: The supply_line_id of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :rtype: str
        """
        return self._supply_line_id

    @supply_line_id.setter
    def supply_line_id(self, supply_line_id):
        """Sets the supply_line_id of this BatchBaseSupplyPriceGroupPrice.


        :param supply_line_id: The supply_line_id of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :type: str
        """
        if supply_line_id is None:
            raise ValueError("Invalid value for `supply_line_id`, must not be `None`")  # noqa: E501

        self._supply_line_id = supply_line_id

    @property
    def price_group_id(self):
        """Gets the price_group_id of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501


        :return: The price_group_id of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :rtype: str
        """
        return self._price_group_id

    @price_group_id.setter
    def price_group_id(self, price_group_id):
        """Sets the price_group_id of this BatchBaseSupplyPriceGroupPrice.


        :param price_group_id: The price_group_id of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :type: str
        """
        if price_group_id is None:
            raise ValueError("Invalid value for `price_group_id`, must not be `None`")  # noqa: E501

        self._price_group_id = price_group_id

    @property
    def price_per_piece(self):
        """Gets the price_per_piece of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501


        :return: The price_per_piece of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :rtype: Price
        """
        return self._price_per_piece

    @price_per_piece.setter
    def price_per_piece(self, price_per_piece):
        """Sets the price_per_piece of this BatchBaseSupplyPriceGroupPrice.


        :param price_per_piece: The price_per_piece of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :type: Price
        """
        if price_per_piece is None:
            raise ValueError("Invalid value for `price_per_piece`, must not be `None`")  # noqa: E501

        self._price_per_piece = price_per_piece

    @property
    def price_group_type(self):
        """Gets the price_group_type of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501


        :return: The price_group_type of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :rtype: PriceGroupType
        """
        return self._price_group_type

    @price_group_type.setter
    def price_group_type(self, price_group_type):
        """Sets the price_group_type of this BatchBaseSupplyPriceGroupPrice.


        :param price_group_type: The price_group_type of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :type: PriceGroupType
        """
        if price_group_type is None:
            raise ValueError("Invalid value for `price_group_type`, must not be `None`")  # noqa: E501

        self._price_group_type = price_group_type

    @property
    def price_per_piece_last_modified(self):
        """Gets the price_per_piece_last_modified of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501

        This field is set when the price has been changed by the supplier.  # noqa: E501

        :return: The price_per_piece_last_modified of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :rtype: datetime
        """
        return self._price_per_piece_last_modified

    @price_per_piece_last_modified.setter
    def price_per_piece_last_modified(self, price_per_piece_last_modified):
        """Sets the price_per_piece_last_modified of this BatchBaseSupplyPriceGroupPrice.

        This field is set when the price has been changed by the supplier.  # noqa: E501

        :param price_per_piece_last_modified: The price_per_piece_last_modified of this BatchBaseSupplyPriceGroupPrice.  # noqa: E501
        :type: datetime
        """
        if price_per_piece_last_modified is None:
            raise ValueError("Invalid value for `price_per_piece_last_modified`, must not be `None`")  # noqa: E501

        self._price_per_piece_last_modified = price_per_piece_last_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchBaseSupplyPriceGroupPrice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchBaseSupplyPriceGroupPrice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
