# coding: utf-8

"""
    Main - Floriday Suppliers API

    ﻿Every endpoint requires at least the `role:app` scope and the header `X-Api-Key` populated with your given API-key. Most endpoints also require an additional scope which is listed in their descriptions.  - 🗝 [Authorization server (staging)](https://idm.staging.floriday.io/oauth2/ausmw6b47z1BnlHkw0h7/.well-known/oauth-authorization-server) - 🗝 [Authorization server (live)](https://idm.floriday.io/oauth2/aus3testdcf2vyfs70i7/.well-known/oauth-authorization-server) - 📚 [Documentation](https://developer.floriday.io/docs/welcome) - ▶ [Coding screencast: getting started (NL)](https://www.youtube.com/watch?v=fdqzP7_Y_s8)  ---  _The current state of this version 2024v1 is **Main**._ * This version will be deprecated after October 2024. * This version will be removed after April 2025.  ---  🔗 2023v2: [Customers API](https://api.staging.floriday.io/customers-api-2023v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2023v2/swagger/index.html) 🔗 2024v1: [Customers API](https://api.staging.floriday.io/customers-api-2024v1/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v1/swagger/index.html) 🔗 2024v2: [Customers API](https://api.staging.floriday.io/customers-api-2024v2/swagger/index.html) | [Suppliers API](https://api.staging.floriday.io/suppliers-api-2024v2/swagger/index.html)   # noqa: E501

    OpenAPI spec version: 2024v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ContractTradeItemGroupTradeItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'trade_item_id': 'str',
        'is_primary': 'bool',
        'packing_configuration': 'PackingConfigurationBase',
        'is_deleted': 'bool'
    }

    attribute_map = {
        'trade_item_id': 'tradeItemId',
        'is_primary': 'isPrimary',
        'packing_configuration': 'packingConfiguration',
        'is_deleted': 'isDeleted'
    }

    def __init__(self, trade_item_id=None, is_primary=None, packing_configuration=None, is_deleted=None):  # noqa: E501
        """ContractTradeItemGroupTradeItem - a model defined in Swagger"""  # noqa: E501
        self._trade_item_id = None
        self._is_primary = None
        self._packing_configuration = None
        self._is_deleted = None
        self.discriminator = None
        self.trade_item_id = trade_item_id
        self.is_primary = is_primary
        self.packing_configuration = packing_configuration
        self.is_deleted = is_deleted

    @property
    def trade_item_id(self):
        """Gets the trade_item_id of this ContractTradeItemGroupTradeItem.  # noqa: E501


        :return: The trade_item_id of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :rtype: str
        """
        return self._trade_item_id

    @trade_item_id.setter
    def trade_item_id(self, trade_item_id):
        """Sets the trade_item_id of this ContractTradeItemGroupTradeItem.


        :param trade_item_id: The trade_item_id of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :type: str
        """
        if trade_item_id is None:
            raise ValueError("Invalid value for `trade_item_id`, must not be `None`")  # noqa: E501

        self._trade_item_id = trade_item_id

    @property
    def is_primary(self):
        """Gets the is_primary of this ContractTradeItemGroupTradeItem.  # noqa: E501


        :return: The is_primary of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :rtype: bool
        """
        return self._is_primary

    @is_primary.setter
    def is_primary(self, is_primary):
        """Sets the is_primary of this ContractTradeItemGroupTradeItem.


        :param is_primary: The is_primary of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :type: bool
        """
        if is_primary is None:
            raise ValueError("Invalid value for `is_primary`, must not be `None`")  # noqa: E501

        self._is_primary = is_primary

    @property
    def packing_configuration(self):
        """Gets the packing_configuration of this ContractTradeItemGroupTradeItem.  # noqa: E501


        :return: The packing_configuration of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :rtype: PackingConfigurationBase
        """
        return self._packing_configuration

    @packing_configuration.setter
    def packing_configuration(self, packing_configuration):
        """Sets the packing_configuration of this ContractTradeItemGroupTradeItem.


        :param packing_configuration: The packing_configuration of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :type: PackingConfigurationBase
        """
        if packing_configuration is None:
            raise ValueError("Invalid value for `packing_configuration`, must not be `None`")  # noqa: E501

        self._packing_configuration = packing_configuration

    @property
    def is_deleted(self):
        """Gets the is_deleted of this ContractTradeItemGroupTradeItem.  # noqa: E501


        :return: The is_deleted of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :rtype: bool
        """
        return self._is_deleted

    @is_deleted.setter
    def is_deleted(self, is_deleted):
        """Sets the is_deleted of this ContractTradeItemGroupTradeItem.


        :param is_deleted: The is_deleted of this ContractTradeItemGroupTradeItem.  # noqa: E501
        :type: bool
        """
        if is_deleted is None:
            raise ValueError("Invalid value for `is_deleted`, must not be `None`")  # noqa: E501

        self._is_deleted = is_deleted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContractTradeItemGroupTradeItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContractTradeItemGroupTradeItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
